sonata_admin:
    title: 'VPL Admin'
    search: false
    dashboard:
        groups:
            goods:
                label: Товары
                keep_open: true
            site:
                label: Сайт
                keep_open: true
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    persist_filters: false
    assets:
        extra_javascripts:
            - 'assets/js/admin.js'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_form:
    form_type: standard
