<?php

namespace AppBundle\Repository;

/**
 * ProductInfoLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInfoLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
