<?php

namespace AppBundle\Repository;

/**
 * ProductInfoGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInfoGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
