# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    admin_username: '%env(ADMIN_USERNAME)%'
    admin_password: '%env(ADMIN_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Admin\CategoryAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Category
                manager_type: orm
                group: goods
                label: Категории
                priority: 10

    App\Admin\SubcategoryAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Subcategory
                manager_type: orm
                group: goods
                label: Подкатегории
                priority: 9

    App\Admin\ProductAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Product
                manager_type: orm
                group: goods
                label: Продукты
                priority: 8

    App\Admin\ManufacturerAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Manufacturer
                manager_type: orm
                group: goods
                label: Производители
                priority: 7

    App\Admin\PropertyAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Property
                manager_type: orm
                group: goods
                label: Свойства
                priority: 6

    App\Admin\PropertySetAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\PropertySet
                controller: App\Controller\PropertySetAdminController
                manager_type: orm
                group: goods
                label: Наборы свойств
                priority: 5

    App\Admin\StyleAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\Style
                manager_type: orm
                group: goods
                label: Дизайн
                priority: 4

    App\Admin\ProductTypeAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\ProductType
                manager_type: orm
                label: Типы продуктов

    App\Admin\ProductInfoMiddleAdmin:
        tags:
            -
                name: sonata.admin
                model_class: App\Entity\ProductInfoMiddle
                manager_type: orm
                label: Средний инфоблок

    App\Admin\ProductInfoBottomAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\ProductInfoBottom
                manager_type: orm
                label: Нижний инфоблок

    App\Admin\ProductInfoMiddleGalleryAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\ProductInfoMiddleGallery
                manager_type: orm
                label: Галерея инфоблока

    App\Admin\CategoryPropertyAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\CategoryProperty
                manager_type: orm
                label: Свойства категорий

    App\Admin\ProductPropertyAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\ProductProperty
                manager_type: orm
                label: Свойства продуктов

    App\Admin\PropertyItemAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\PropertyItem
                manager_type: orm
                label: Элементы набора свойств

    App\Admin\ProductManufacturerAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\ProductManufacturer
                manager_type: orm
                label: Производители продуктов

    App\Admin\StyleImgAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\StyleImg
                manager_type: orm
                label: Изображения стиля

    App\Admin\StyleInfoBottomAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\StyleInfoBottom
                manager_type: orm
                label: Нижний инфоблок

    App\Admin\MainPageAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\MainPage
                manager_type: orm
                group: site
                label: Главная страница

    App\Admin\MainPageImagesAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\MainPageImages
                manager_type: orm
                group: site
                label: Главная. Первая строка

    App\Admin\MiscAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\Misc
                manager_type: orm
                group: site
                label: Разное

    App\Admin\UserAdmin:
        tags:
            -   name: sonata.admin
                model_class: App\Entity\User
                manager_type: orm
                group: site
                label: Пользователи
