sonata_admin:
#    security:
#        handler: sonata.admin.security.handler.role
#
#        role_admin: ROLE_ADMIN
#        role_super_admin: ROLE_SUPER_ADMIN
    title: 'VPL Admin'
    #title_logo: bundles/sonataadmin/logo_title.png
    search: false
    dashboard:
        groups:
            goods:
                label: Товары
            site:
                label: Сайт
    persist_filters: false
    assets:
        extra_javascripts:
            - 'assets/js/admin.js'


sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
