app_index:
    path: /
    defaults: { _controller: AppBundle:Default:index }
app_categories:
    path: /categories
    defaults: { _controller: AppBundle:Categories:index }
app_category:
    path: /category/{id}
    defaults: { _controller: AppBundle:Category:index }
    requirements:
        page: '\d+'
app_subcategory:
    path: /subcategory/{id}
    defaults: { _controller: AppBundle:Subcategory:index }
    requirements:
        page: '\d+'
app_product:
    path: /product/{id}
    defaults: { _controller: AppBundle:Product:index }
    requirements:
        page: '\d+'
app_design:
    path: /design
    defaults: { _controller: AppBundle:Design:index }
#app_design_id:
#    path: /design/{id}
#    defaults: { _controller: AppBundle:Design:index }
#    requirements:
#        page: '\d+'
app_property:
    path: /property/{id}
    defaults: { _controller: AppBundle:Property:index }
    requirements:
        page: '\d+'
app_manufacturer:
    path: /manufacturer/{id}
    defaults: { _controller: AppBundle:Manufacturer:index }
    requirements:
        page: '\d+'
app_property_set:
    path: /property-set/{id}
    defaults: { _controller: AppBundle:PropertySet:index }
    requirements:
        page: '\d+'
app_contact:
    path: /contact
    defaults: { _controller: AppBundle:Contact:index }
app_feedback:
    path: /feedback
    defaults: { _controller: AppBundle:Feedback:index }

app_login:
    path: /login/
    defaults: { _controller: AppBundle:Sign:login }
app_logout:
    path: /logout