services:
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Категории }
        public: true

    admin.subcategory:
        class: AppBundle\Admin\SubcategoryAdmin
        arguments: [~, AppBundle\Entity\Subcategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Подкатегории }
        public: true
