services:
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: goods, label: Категории }
        public: true

    admin.subcategory:
        class: AppBundle\Admin\SubcategoryAdmin
        arguments: [~, AppBundle\Entity\Subcategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: goods, label: Подкатегории }
        public: true

    admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: goods, label: Продукты }
        public: true

    admin.property:
        class: AppBundle\Admin\PropertyAdmin
        arguments: [~, AppBundle\Entity\Property, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: goods, label: Свойства }
        public: true

    admin.productType:
        class: AppBundle\Admin\ProductTypeAdmin
        arguments: [~, AppBundle\Entity\ProductType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Типы продуктов }
        public: true

    admin.productInfoMiddle:
        class: AppBundle\Admin\ProductInfoMiddleAdmin
        arguments: [~, AppBundle\Entity\ProductInfoMiddle, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Средний инфоблок }
        public: true

    admin.productInfoBottom:
        class: AppBundle\Admin\ProductInfoBottomAdmin
        arguments: [~, AppBundle\Entity\ProductInfoBottom, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Нижний инфоблок }
        public: true

    admin.productInfoMiddleGallery:
        class: AppBundle\Admin\ProductInfoMiddleGalleryAdmin
        arguments: [~, AppBundle\Entity\ProductInfoMiddleGallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Галерея инфоблока }
        public: true

    admin.categoryProperty:
        class: AppBundle\Admin\CategoryPropertyAdmin
        arguments: [~, AppBundle\Entity\CategoryProperty, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Свойства категорий }
        public: true

    admin.productProperty:
        class: AppBundle\Admin\ProductPropertyAdmin
        arguments: [~, AppBundle\Entity\ProductProperty, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Свойства продуктов }
        public: true
