AppBundle\Entity\CategoryProperty:
    type: entity
    table: category_property
    indexes:
        ix__category_property__category_id:
            columns:
                - category_id
        ix__category_property__property_id:
            columns:
                - property_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        seq:
            type: integer
            nullable: false
            options:
                unsigned: true
        created:
            type: datetime
            nullable: false
            options:
                default: '2000-01-01 00:00:00'
        modified:
            type: datetime
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        property:
            targetEntity: Property
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                property_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: categoryProperty
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
