AppBundle\Entity\ProductProperty:
    type: entity
    table: product_property
    indexes:
        ix__product_property__product_id:
            columns:
                - product_id
        ix__product_property__category_property_id:
            columns:
                - category_property_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        img:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        seq:
            type: smallint
            nullable: false
            options:
                unsigned: true
        created:
            type: datetime
            nullable: false
            options:
                default: '2000-01-01 00:00:00'
        modified:
            type: datetime
            nullable: true
    manyToOne:
        categoryProperty:
            targetEntity: CategoryProperty
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_property_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
