AppBundle\Entity\ProductInfo:
    type: entity
    table: product_info
    indexes:
        ix__product_info__product_id:
            columns:
                - product_id
        ix__prod_inf__prod_inf_loc_code:
            columns:
                - product_info_location_code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        text:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        seq:
            type: integer
            nullable: false
            options:
                unsigned: true
        isGallery:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_gallery
        created:
            type: datetime
            nullable: false
            options:
                default: '2000-01-01 00:00:00'
        modified:
            type: datetime
            nullable: true
    manyToOne:
        productInfoLocationCode:
            targetEntity: ProductInfoLocation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_info_location_code:
                    referencedColumnName: code
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
