AppBundle\Entity\ProductType:
    type: entity
    table: product_type
    indexes:
        ix__product_type__product_id:
            columns:
                - product_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        img:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        seq:
            type: smallint
            nullable: false
            options:
                unsigned: true
        created:
            type: datetime
            nullable: false
            options:
                default: '2000-01-01 00:00:00'
        modified:
            type: datetime
            nullable: true
    manyToOne:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
