AppBundle\Entity\ProductInfoGallery:
    type: entity
    repositoryClass: AppBundle\Repository\ProductInfoGalleryRepository
    table: product_info_gallery
    indexes:
        ix__product_info_gallery__product_info_id:
            columns:
                - product_info_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        img:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        seq:
            type: integer
            nullable: false
            options:
                unsigned: true
        created:
            type: datetime
            nullable: false
            options:
                default: '2000-01-01 00:00:00'
        modified:
            type: datetime
            nullable: true
    manyToOne:
        productInfo:
            targetEntity: ProductInfo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_info_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
