AppBundle\Entity\Product:
    type: entity
    table: product
    indexes:
        ix__product__subcategory_id:
            columns:
                - subcategory_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        descriptionFull:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_full
        img:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        created:
            type: datetime
            nullable: false
            options:
                default: '2000-01-01 00:00:00'
        modified:
            type: datetime
            nullable: true
    manyToOne:
        subcategory:
            targetEntity: Subcategory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                subcategory_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        categoryProperty:
            targetEntity: CategoryProperty
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: product
            joinTable:
                name: product_property
                joinColumns:
                    -
                        name: product_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: category_property_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
